### ISSUE TITLE
cannot load such file -- nokogiri/nokogiri (LoadError)

### ISSUE THREAD

**Issue by ktlim86** [nsidc/vagrant-vsphere#185]
Hi,

I am new to this plugin. I tried to follow the instructions in the README.md.
Unfortunately I am running into a problem. Below is the error message
```
C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:29:in `require': cannot load such file -- nokogir
i/nokogiri (LoadError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:29:in `rescue in <top (required)>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:25:in `<top (required)>'
        from C:/Users/iMerino/.vagrant.d/gems/gems/rbvmomi-1.8.2/lib/rbvmomi/trivial_soap.rb:4:in `require'
        from C:/Users/iMerino/.vagrant.d/gems/gems/rbvmomi-1.8.2/lib/rbvmomi/trivial_soap.rb:4:in `<top (required)>'
        from C:/Users/iMerino/.vagrant.d/gems/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:4:in `require'
        from C:/Users/iMerino/.vagrant.d/gems/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:4:in `<top (required)>'
        from C:/Users/iMerino/.vagrant.d/gems/gems/rbvmomi-1.8.2/lib/rbvmomi.rb:11:in `require'
        from C:/Users/iMerino/.vagrant.d/gems/gems/rbvmomi-1.8.2/lib/rbvmomi.rb:11:in `<top (required)>'
        from C:/Users/iMerino/.vagrant.d/gems/gems/vagrant-vsphere-1.7.0/lib/vSphere/action/connect_vsphere.rb:1:in `require'
        from C:/Users/iMerino/.vagrant.d/gems/gems/vagrant-vsphere-1.7.0/lib/vSphere/action/connect_vsphere.rb:1:in `<top (required)>'

        from C:/Users/iMerino/.vagrant.d/gems/gems/vagrant-vsphere-1.7.0/lib/vSphere/action.rb:164:in `block in action_get_state'
        from C:/Users/iMerino/.vagrant.d/gems/gems/vagrant-vsphere-1.7.0/lib/vSphere/action.rb:161:in `tap'
        from C:/Users/iMerino/.vagrant.d/gems/gems/vagrant-vsphere-1.7.0/lib/vSphere/action.rb:161:in `action_get_state'
        from C:/Users/iMerino/.vagrant.d/gems/gems/vagrant-vsphere-1.7.0/lib/vSphere/provider.rb:12:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:187:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
        from C:/Users/iMerino/.vagrant.d/gems/gems/vagrant-vsphere-1.7.0/lib/vSphere/provider.rb:22:in `state'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:501:in `state'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:144:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:79:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:79:in `machine'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:663:in `machine'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:177:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:201:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:201:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:183:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:183:in `with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/up/command.rb:89:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:278:in `block (2 levels) in batch'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:276:in `tap'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:276:in `block in batch'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:275:in `synchronize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:275:in `batch'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/up/command.rb:88:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:302:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:174:in `<main>'
```

Any help will be appreciated. Thanks. :)

**Comment by albeekj** [comment]
If you are using windows the problem might be the ruby version vagrant is using.  ruby 2.2.0 is not supported for nokogiri in windows.

**Comment by ktlim86** [comment]
HI albeekj,

Thanks for the quick reply! I will try that. :)

**Comment by jschwartz73** [comment]
I was able to get it working with the help of this article:
https://jasonbarto.com/installing-vagrant-on-windows/
