### ISSUE TITLE
InvalidLogin: Cannot complete login due to an incorrect user name or password

### ISSUE THREAD

**Issue by ticktockhouse** [nsidc/vagrant-vsphere#248]
Hi,

I'm getting the following message:
```
........
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::VSphere::Errors::VSphereError: InvalidLogin: Cannot complete login due to an incorrect user name or password.>
ERROR vagrant: InvalidLogin: Cannot complete login due to an incorrect user name or password.
ERROR vagrant: /firstpool/data/vagrant-home/gems/2.3.4/gems/vagrant-vsphere-1.12.1/lib/vSphere/action/connect_vsphere.rb:23:in `rescue in call'
/data/vagrant-home/gems/2.3.4/gems/vagrant-vsphere-1.12.1/lib/vSphere/action/connect_vsphere.rb:14:in `call'
........
INFO interface: error: InvalidLogin: Cannot complete login due to an incorrect user name or password.
InvalidLogin: Cannot complete login due to an incorrect user name or password.
```
There is an event in the vsphere log:

05/10/2017, 10:10:33     Cannot login username@vsphere.local@ip.of.my.workstation

This is my Vagrantfile:
```
Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.box_url = "./example_box/dummy.box"

  config.vm.provider :vsphere do |vsphere|
    vsphere.host = "ip.of.vsphere.host"
    vsphere.compute_resource_name = "10.1.47.26"
    vsphere.user = "jsteele@vsphere.local"
    #vsphere.user = "username@vsphere.local"
    vsphere.password = "awesomely_uncrackable_password"
    vsphere.template_name = "ubuntu-16.04-vagrant"
    vsphere.insecure = true
  end 
end
```
I'm not sure if the plugin is appending the IP of my workstation, or whether it's a setting in vsphere itself, but it seems that this is what is causing the issue. Can anyone shed any light on this?

**Comment by Hickory420** [comment]
I know this is old. And it's not a true automated solution, but my super awesome uncrackable password has issues as well. You may have already found a fix/workaround for it, but (aside from escaping special characters), you can use `:ask`

```
Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.box_url = "./example_box/dummy.box"

  config.vm.provider :vsphere do |vsphere|
    vsphere.host = "ip.of.vsphere.host"
    vsphere.compute_resource_name = "10.1.47.26"
    vsphere.user = "jsteele@vsphere.local"
    #vsphere.user = "username@vsphere.local"
    # If you have a multi server Vagrantfile, it will ask you for each server because it's a separate connection
    vsphere.password = :ask
    vsphere.template_name = "ubuntu-16.04-vagrant"
    vsphere.insecure = true
  end 
end
```

**Comment by reyesjos500** [comment]
I am getting the same issue. It is a hit/miss. Sometimes work, sometimes doesn't. I am getting the error InvalidLogin: Cannot complete login due to an incorrect user name or password.
The problem seems to be the connection to vcenter. As I said, it is a hit/miss. If anyone found a solution, please post.
