### ISSUE TITLE
Cannot install in vagrant 2.3.4 from Debian

### ISSUE THREAD

**Issue by cquike** [nsidc/vagrant-vsphere#303]
I am using vagrant 2.3.4 from Debian testing and I have an error when installing the vsphere provider:
```
$ vagrant plugin install vagrant-vsphere  
Installing the 'vagrant-vsphere' plugin. This can take a few minutes...
/usr/lib/ruby/vendor_ruby/rubygems/specification.rb:2238:in `check_version_conflict': can't activate json-2.6.3, already activated json-2.6.1 (Gem::LoadError)
	from /usr/lib/ruby/vendor_ruby/rubygems/specification.rb:1375:in `activate'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/bundler.rb:756:in `block in activate_solution'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/bundler.rb:753:in `each'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/bundler.rb:753:in `activate_solution'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/bundler.rb:593:in `internal_install'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/bundler.rb:355:in `install'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/plugin/manager.rb:138:in `block in install_plugin'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/plugin/manager.rb:148:in `install_plugin'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/plugins/commands/plugin/action/install_gem.rb:30:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/action/builder.rb:180:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/action/runner.rb:101:in `block in run'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/action/runner.rb:101:in `run'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/plugins/commands/plugin/command/base.rb:14:in `action'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/plugins/commands/plugin/command/install.rb:70:in `block in execute'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/plugins/commands/plugin/command/install.rb:69:in `each'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/plugins/commands/plugin/command/install.rb:69:in `execute'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/plugins/commands/plugin/command/root.rb:66:in `execute'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/cli.rb:67:in `execute'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/environment.rb:301:in `cli'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/bin/vagrant:243:in `<top (required)>'
	from /usr/bin/vagrant:25:in `load'
	from /usr/bin/vagrant:25:in `<main>'

```

```
$ vagrant --version
Vagrant 2.3.4

```

I have other plugins installed, two from Debian repos and two other ones installed with vagrant plugin without problems:
```
$ vagrant plugin list
vagrant-libvirt (0.11.2, system)
vagrant-lxc (1.4.3, system)
vagrant-managed-servers (0.8.0, global)
virtualbox (0.8.6, global)

```

Thank you!

**Comment by cquike** [comment]
I can indeed see that the version of ruby json installed in the system is 2.6.1:
```
$ grep VERSION /usr/lib/ruby/3.1.0/json/version.rb
  VERSION         = '2.6.1'

```

**Comment by cquike** [comment]
This is the version of ruby:
```
$ ruby --version
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]

```
