### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by vralfy** [nsidc/vagrant-vsphere#75]
ERROR warden: Error occurred: no implicit conversion of nil into String
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-d69bac12b3c8d67265f557bab57df204
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #Vagrant::Action::Builder:0x007fc8c9073520
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::VSphere::Errors::VSphereError: no implicit conversion of nil into String>
ERROR vagrant: no implicit conversion of nil into String
ERROR vagrant: /home/nspecht/.vagrant.d/gems/gems/vagrant-vsphere-0.10.0/lib/vSphere/action/connect_vsphere.rb:23:in `rescue in call'
/home/nspecht/.vagrant.d/gems/gems/vagrant-vsphere-0.10.0/lib/vSphere/action/connect_vsphere.rb:14:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/config_validate.rb:25:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builder.rb:116:in`call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in`busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:196:in`action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:173:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/environment.rb:434:in`lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in`action'
/opt/vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: no implicit conversion of nil into String
no implicit conversion of nil into String
 INFO interface: Machine: error-exit ["VagrantPlugins::VSphere::Errors::VSphereError", "no implicit conversion of nil into String"]

**Comment by rylarson** [comment]
Can you post a redacted Vagrantfile that reproduces this error?
